### ISSUE TITLE
Can't relicense a derivative work

### ISSUE THREAD

**Issue by konklone** [18F/laptop#1]
This is a derivative work of thoughtbot's `laptop` project, and the README and `mac` script are primarily copied from the original.

That's totally fine, but we can't take thoughtbot's intellectual property and release it as public domain. The LICENSE and README should include thoughtbot's original copyright license, and then note that subsequent changes we've made are in the public domain. 

The Free Software Foundation [notes in their FAQ](http://www.gnu.org/licenses/gpl-faq.html#GPLUSGovAdd) that the improved version, as a whole, should still be considered under its original license. Eventually, the project may veer so far away from the original that that is no longer the case, and the MIT part can be presented as the exception.

**Comment by konklone** [comment]
(Also, happy to do a PR for this if you'd like.)

**Comment by afeld** [comment]
> Can't relicense a derivative work

IANAL, but I don't think this is the case for MIT. It specifically mentions sublicensing, which I think would apply here, with or without modification.

> The Free Software Foundation notes in their FAQ that the improved version, as a whole, should still be considered under its original license

I believe that is specific to the GPL.

**Comment by konklone** [comment]
> IANAL, but I don't think this is the case for MIT. It specifically mentions sublicensing, which I think would apply here, with or without modification.

It allows sublicensing, but sublicensing doesn't remove thoughtbot's original copyright over the work. Dedicating their code to the public domain would, and so I think it's not allowed. This is also why I try hard to use "dedicating" rather than "licensing" when discussing CC0/PD (though I often slip).

The MIT license also states that its own text needs to be present with the distribution of derivative works, even sublicensed ones.

>> The Free Software Foundation notes in their FAQ that the improved version, as a whole, should still be considered under its original license
> 
> I believe that is specific to the GPL.

Could be, though I believe it's not -- so if that became an issue, we could dig into it more. I think it's not that relevant here, though.

**Comment by monfresh** [comment]
Thanks for pointing this out, @konklone. I'd love a PR from you.
