### ISSUE TITLE
make permissions on git sekrets rules non-executable if possible

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/laptop#102]
So I noticed that the default permissions are executable for the rules files.
-rwxr-xr-x

Prefer to have permissions for these files look like:
-rw-r--r--

Is there a need for these to be executable?

### OS X version 
OSX 10.11.6
Darwin I09R9J-72S8FVH8.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64

These match https://github.com/18F/laptop/tree/seekret/seekret-rules

**Comment by LinuxBozo** [comment]
Mat and I discovered this was false postive. Closing.
