### ISSUE TITLE
[ git-seekrets ] Thought a NEW RELIC key was an AWS key

### ISSUE THREAD

**Issue by rogeruiz** [18F/laptop#112]
Because the AWS rules check for a `KEY` and `NEW_RELIC_LICENSE_KEY` contains that word, we'll need to have an unmatch somewhere to avoid the other one.

### Acceptance Criteria

- [x] AWS shouldn't match the New Relic license key by not matching `NEW_RELIC`

**Comment by rogeruiz** [comment]
@alain-hoang has started working on this here => https://github.com/18F/laptop/pull/111

**Comment by alain-hoang** [comment]
See [#115](https://github.com/18F/laptop/pull/115) for continued work

**Comment by rogeruiz** [comment]
Closed in #112
