### ISSUE TITLE
Script failing on new mac

### ISSUE THREAD

**Issue by andrewmaier** [18F/laptop#12]
Hey @monfresh,

Tried running this on a new mac and got an error around bundler. I was prompted to install Xcode tools early on and installed the Atom editor. Otherwise, this is a pretty clean slate?

Hugs,
-Andrew

`~/laptop.log`

Changing your shell to zsh ...
Changing shell for andrewmaier.

Installing Homebrew ...
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1
==> The following directories will be made group writable:
/usr/local/.
==> The following directories will have their group set to admin:
/usr/local/.
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/.

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/.
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at e2c6f86 pjproject: add 2.3 bottle.
==> Installation successful!
==> Next steps
Run `brew help` to get started

Updating Homebrew formulas ...
Already up-to-date.

Installing git ...
==> Downloading https://homebrew.bintray.com/bottles/git-2.3.5.yosemite.bottle.tar.gz
==> Pouring git-2.3.5.yosemite.bottle.tar.gz
==> Caveats
The OS X keychain credential helper has been installed to:
  /usr/local/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /usr/local/share/git-core/contrib

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/git/2.3.5: 1363 files,  31M

Installing the_silver_searcher ...
==> Installing dependencies for the_silver_searcher: pcre, xz
==> Installing the_silver_searcher dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.36.yosemite.bottle.tar.gz
==> Pouring pcre-8.36.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.36: 146 files, 5.9M
==> Installing the_silver_searcher dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.1.yosemite.bottle.tar.gz
==> Pouring xz-5.2.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.1: 59 files, 1.7M
==> Installing the_silver_searcher
==> Downloading https://homebrew.bintray.com/bottles/the_silver_searcher-0.29.1.yosemite.bottle.tar.gz
==> Pouring the_silver_searcher-0.29.1.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/the_silver_searcher/0.29.1: 8 files, 112K

Tapping gapple/services...
Tapped 0 formulae

Installing postgresql ...
==> Installing dependencies for postgresql: openssl, readline
==> Installing postgresql dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.tar.gz
==> Pouring openssl-1.0.2a-1.yosemite.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2a-1: 463 files,  18M
==> Installing postgresql dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.yosemite.bottle.tar.gz
==> Pouring readline-6.3.8.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2.1M
==> Installing postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.4.1.yosemite.bottle.1.tar.gz
==> Pouring postgresql-9.4.1.yosemite.bottle.1.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.4) of PostgreSQL, see:
  http://www.postgresql.org/docs/9.4/static/upgrading.html

To have launchd start postgresql at login:
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
Then to load postgresql now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
Or, if you don't want/need launchctl, you can just run:
    postgres -D /usr/local/var/postgres
==> /usr/local/Cellar/postgresql/9.4.1/bin/initdb /usr/local/var/postgres
==> Summary
🍺  /usr/local/Cellar/postgresql/9.4.1: 2996 files,  40M

Restarting postgres...
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)

Installing mysql ...
==> Downloading https://homebrew.bintray.com/bottles/mysql-5.6.23.yosemite.bottle.tar.gz
==> Pouring mysql-5.6.23.yosemite.bottle.tar.gz
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

To connect:
    mysql -uroot

To have launchd start mysql at login:
    ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
Then to load mysql now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
Or, if you don't want/need launchctl, you can just run:
    mysql.server start
==> /usr/local/Cellar/mysql/5.6.23/bin/mysql_install_db --verbose --user=andrewmaier --basedir=/usr/local/Cellar/mysql/5.6.23 --datadir=/usr/local/var/mysql --tmpdir=/tmp
==> Summary
🍺  /usr/local/Cellar/mysql/5.6.23: 9687 files, 339M

Restarting mysql...
==> Successfully started `mysql` (label: homebrew.mxcl.mysql)
Starting MySQL
 SUCCESS! 

Installing redis ...
==> Downloading https://homebrew.bintray.com/bottles/redis-2.8.19.yosemite.bottle.tar.gz
==> Pouring redis-2.8.19.yosemite.bottle.tar.gz
==> Caveats
To have launchd start redis at login:
    ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
Then to load redis now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
Or, if you don't want/need launchctl, you can just run:
    redis-server /usr/local/etc/redis.conf
==> Summary
🍺  /usr/local/Cellar/redis/2.8.19: 10 files, 1.4M

Restarting redis...
==> Successfully started `redis` (label: homebrew.mxcl.redis)

Installing imagemagick ...
==> Installing dependencies for imagemagick: libtool, jpeg, libpng, freetype
==> Installing imagemagick dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bottle.tar.gz
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing imagemagick dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.tar.gz
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing imagemagick dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.16.yosemite.bottle.tar.gz
==> Pouring libpng-1.6.16.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.16: 17 files, 1.3M
==> Installing imagemagick dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.5.5.yosemite.bottle.tar.gz
==> Pouring freetype-2.5.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.5.5: 60 files, 2.6M
==> Installing imagemagick
==> Downloading https://homebrew.bintray.com/bottles/imagemagick-6.9.1-0.yosemite.bottle.tar.gz
==> Pouring imagemagick-6.9.1-0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/6.9.1-0: 1442 files,  22M

Installing qt ...
==> Downloading https://homebrew.bintray.com/bottles/qt-4.8.6.yosemite.bottle.6.tar.gz
==> Pouring qt-4.8.6.yosemite.bottle.6.tar.gz
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

.app bundles were installed.
Run `brew linkapps qt` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/qt/4.8.6: 2790 files, 122M

Installing hub ...
==> Downloading https://homebrew.bintray.com/bottles/hub-2.2.0.yosemite.bottle.tar.gz
==> Pouring hub-2.2.0.yosemite.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/hub/2.2.0: 9 files, 9.5M

Installing node ...
==> Downloading https://homebrew.bintray.com/bottles/node-0.12.2_1.yosemite.bottle.tar.gz
==> Pouring node-0.12.2_1.yosemite.bottle.tar.gz
==> Caveats
If you update npm itself, do NOT use the npm update command.
The upstream-recommended way to update npm is:
  npm install -g npm@latest

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/0.12.2_1: 2603 files,  28M

Installing python3 ...
==> Installing dependencies for python3: sqlite, gdbm
==> Installing python3 dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.8.3.yosemite.bottle.tar.gz
==> Pouring sqlite-3.8.8.3.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.8.8.3: 9 files, 2.1M
==> Installing python3 dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.11.yosemite.bottle.2.tar.gz
==> Pouring gdbm-1.11.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/gdbm/1.11: 17 files, 532K
==> Installing python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.4.3.yosemite.bottle.8.tar.gz
==> Pouring python3-3.4.3.yosemite.bottle.8.tar.gz
==> Caveats
Pip and setuptools have been installed. To update them
  pip3 install --upgrade pip setuptools

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.4/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python3` to symlink these to /Applications.
==> /usr/local/Cellar/python3/3.4.3/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.4.3/bin --install-lib=/usr/local/lib/python3.4/site-packages
==> /usr/local/Cellar/python3/3.4.3/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.4.3/bin --install-lib=/usr/local/lib/python3.4/site-packages
==> Summary
🍺  /usr/local/Cellar/python3/3.4.3: 4643 files,  81M
You are using pip version 6.1.0, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Installing virtualenvwrapper...
You are using pip version 6.1.0, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting virtualenvwrapper
  Downloading virtualenvwrapper-4.3.2.tar.gz (86kB)
Collecting virtualenv (from virtualenvwrapper)
  Downloading virtualenv-12.1.1-py2.py3-none-any.whl (1.6MB)
Collecting virtualenv-clone (from virtualenvwrapper)
  Downloading virtualenv-clone-0.2.5.tar.gz
Collecting stevedore (from virtualenvwrapper)
  Downloading stevedore-1.3.0-py2.py3-none-any.whl
  Skipping requirement: argparse (from stevedore->virtualenvwrapper) because argparse is a stdlib package
Collecting pbr!=0.7,<1.0,>=0.6 (from stevedore->virtualenvwrapper)
  Downloading pbr-0.10.8-py2.py3-none-any.whl (70kB)
Collecting six>=1.9.0 (from stevedore->virtualenvwrapper)
  Downloading six-1.9.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/local/lib/python3.4/site-packages/pip-6.1.0-py3.4.egg (from pbr!=0.7,<1.0,>=0.6->stevedore->virtualenvwrapper)
Installing collected packages: virtualenv, virtualenv-clone, pbr, six, stevedore, virtualenvwrapper
  Running setup.py install for virtualenv-clone
  Running setup.py install for virtualenvwrapper
Successfully installed pbr-0.10.8 six-1.9.0 stevedore-1.3.0 virtualenv-12.1.1 virtualenv-clone-0.2.5 virtualenvwrapper-4.3.2

Installing RVM and the latest Ruby...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   184  100   184    0     0    215      0 --:--:-- --:--:-- --:--:--   215

100 22817  100 22817    0     0  16640      0  0:00:01  0:00:01 --:--:-- 16640
Turning on auto dotfiles mode.
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
Found PGP signature at: 'https://github.com/wayneeseguin/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Installing RVM to /Users/andrewmaier/.rvm/
    Adding rvm PATH line to /Users/andrewmaier/.profile /Users/andrewmaier/.mkshrc /Users/andrewmaier/.bashrc /Users/andrewmaier/.zshrc.
    Adding rvm loading line to /Users/andrewmaier/.profile /Users/andrewmaier/.bash_profile /Users/andrewmaier/.zlogin.
Installation of RVM in /Users/andrewmaier/.rvm/ is almost complete:

  * To start using RVM you need to run `source /Users/andrewmaier/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# andrewmaier,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: [32mhttp://rvm.io/help [33mand [32mhttps://twitter.com/rvm_io
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.2.1.tar.bz2
Checking requirements for osx.
Installing requirements for osx.
[32mUpdating system[0m|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|.
[32mInstalling required packages: autoconf, automake, pkg-config, libyaml, libksba[0m|/-\|/-\|.-\|/-\|/-.|/-\.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.2.1 - #configure
ruby-2.2.1 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6516k  100 6516k    0     0  8590k      0 --:--:-- --:--:-- --:--:-- 8596k
ruby-2.2.1 - #validate archive
ruby-2.2.1 - #extract
ruby-2.2.1 - #validate binary
ruby-2.2.1 - #setup
ruby-2.2.1 - #gemset created /Users/andrewmaier/.rvm/gems/ruby-2.2.1@global
[32mruby-2.2.1 - #importing gemset /Users/andrewmaier/.rvm/gemsets/global.gems[0m|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|.
[32mruby-2.2.1 - #generating global wrappers[0m|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-.
ruby-2.2.1 - #gemset created /Users/andrewmaier/.rvm/gems/ruby-2.2.1
ruby-2.2.1 - #importing gemsetfile /Users/andrewmaier/.rvm/gemsets/default.gems evaluated to empty gem list
[32mruby-2.2.1 - #generating default wrappers[0m|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.-\|/-\.
Updating certificates in '/etc/openssl/cert.pem'.
mkdir: /etc/openssl: Permission denied
mkdir -p "/etc/openssl" failed, retrying with sudo
and sudo mkdir worked
[32mCreating alias default for ruby-2.2.1[0m|/-\|/-\|.-\|/-\|/-.|/-\|/-\|.

  * To start using RVM you need to run `source /Users/andrewmaier/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

Updating Rubygems...
Latest version currently installed. Aborting.

Updating bundler ...
Updating installed gems
Nothing to update

Configuring Bundler ...
mac: line 199: bundle: command not found

**Comment by monfresh** [comment]
Thanks for the report! Was this on Mavericks or Yosemite?

I will try to reproduce this on my test laptop. Perhaps something changed in the latest version of RVM.

**Comment by monfresh** [comment]
Turns out this is due to a change in the output of `gem list bundler --installed`. It now returns `false` whereas before it presumably didn't return anything, so the [gem_install_or_update](https://github.com/18F/laptop/blob/master/mac#L87-95) function thinks that bundler is installed and tries to update it instead of installing it.

Fix coming shortly.

**Comment by monfresh** [comment]
And the plot thickens. RVM stopped installing bundler by default in 1.26.11: https://github.com/wayneeseguin/rvm/commit/dc07790042d78c525d7d52616c78cb2d55c0e764

For some reason, the `gem_install_or_update` function is not properly detecting that bundler is not installed. If instead, I use `gem install bundler` in the script, it works, but it would be preferable to be able to update it. I tried changing the function to this, but it didn't work:
```bash
gem_install_or_update() {
  if gem list "$1" --installed | grep -Fqx "false"; then
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
  else
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  fi
}
```

**Comment by monfresh** [comment]
Figured it out. It's because `rubygems-bundler` and `bundler-unload` are installed, and `gem list bundler --installed` returns `true`, so the solution is to find a better way to check if `bundler` itself is installed.

**Comment by andrewmaier** [comment]
@monfresh I'm on Yosemite :)
