### ISSUE TITLE
Need easier way to run the latest version of the laptop script

### ISSUE THREAD

**Issue by monfresh** [18F/laptop#124]
We haven't done a great job of communicating that the laptop script is meant to be run often, in order to keep your machine up to date. Once the script has been downloaded on a machine, it can be run safely multiple times, and if there is anything that needs to be upgraded, it will do it automatically.

The problem is when the script is updated on the repo, with new tools, or fixes. Given the current instructions to download the `mac` and `Brewfile`, one would have to download them again to get the latest script. This is tedious. It would be better to be able to run something like `mac update`, similar to `brew update`, and have it fetch the latest script and run it.

Another solution could be to clone the repo as the initial setup, but then people would have to remember to `cd` into the directory, then run `git pull`, before running `bash mac`.

Thoughts?

**Comment by LinuxBozo** [comment]
Might be easier to have "the laptop script" pull in both `mac` and `Brewfile` from master instead of having the instructions be to do both with curl manually?

**Comment by monfresh** [comment]
What would the instructions become in that case to run the script?

**Comment by LinuxBozo** [comment]
Would look similar to how git-seekrets is done.

So, this new "laptop script" basically is the old instructions:

```shell
#!/bin/sh

curl --remote-name https://raw.githubusercontent.com/18F/laptop/master/mac
curl --remote-name https://raw.githubusercontent.com/18F/laptop/master/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log

# Maybe do some clean-up here
```

And the new instructions boil down to:
```
curl -s https://raw.githubusercontent.com/18F/laptop/master/NEW-SCRIPT-HERE | sh -
```
Nothing to download.. can be ran multiple times.. always gets the latest changes.

Could use the same approach for an uninstall.

**Comment by monfresh** [comment]
Makes sense. To make it easier to run that command, perhaps we can add an alias to `.zshrc` as part of the script installation, maybe `laptop`?

**Comment by monfresh** [comment]
Done in #131
