### ISSUE TITLE
git-seekrets requires git 2.9.1 for global hooks, but Ubuntu 16.04 ships with git 2.7

### ISSUE THREAD

**Issue by adborden** [18F/laptop#136]
I modified the `seekrets-install` script before running it because I wanted to tweak the installation, also to get around the version check. My understanding is that git 2.9.1 is needed for the global hooks feature, but git-seekrets can still be used with individual repo hooks. I'd like advice on either:
- Is there a recommended way to install git 2.9.1 on ubuntu 16.04?
- What is the suggested way to easily install the hooks on a per-repo basis (maybe via bash alias)?

I'm happy to help with a PR for this.

### OS X version you are using
Ubuntu 16.04

### Did you recently upgrade from a previous OS X version?
N/A

### Are you running the script on a fresh OS X installation?
N/A

### Did you have any of the following tools installed before running the script?
N/A

- Xcode
- Apple's command line tools
- Anything the script installs (see "What it sets up" in the README)

**Comment by cmc333333** [comment]
@adborden we recently found that using a PPA lets you get the latest version of git:
```bash
sudo add-apt-repository ppa:git-core/ppa
sudo apt-get update
git --version
```
which should help

**Comment by adborden** [comment]
:+1: do we want to add this to the README?
