### ISSUE TITLE
Is there a more robust way to automatically fetch the latest rules?

### ISSUE THREAD

**Issue by monfresh** [18F/laptop#142]
I was looking at https://github.com/18F/laptop/blob/master/seekrets-install#L86
which points to this nonexistent URL:
https://raw.githubusercontent.com/18F/laptop/master/seekret-rules

At first, I thought it was a bug, but then I realized that URL is only used to define the prefix, and then for each rule defined at the top in `SEEKRET_DEFAULT_RULES`, it looks for that rule within that prefixed URL.

This seems a little brittle to me because if a new rule is added to that folder in GitHub, that means we have to remember to update `SEEKRET_DEFAULT_RULES` with the new rule.

It would feel more robust to be able to automatically look for all rules within the `seekret-rules` folder on GitHub.

Thoughts?

**Comment by mgwalker** [comment]
The Github API offers [an endpoint to get a list of files](https://api.github.com/repos/18F/laptop/contents/seekret-rules) in a repo.  The `download_url` property is the interesting one.

This bit of script gets the URLs on separate lines, which may be able to replace the `$SEEKRET_DEFAULT_RULES` variable (about to test that theory):

```bash
# fetch contents; filter down to just the lines that include the download_url; match out just the url and toss the rest
curl -s https://api.github.com/repos/18F/laptop/contents/seekret-rules | grep download_url | sed -e 's/.*: "\([^"]*\)".*/\1/'
```
