### ISSUE TITLE
Add Jekyll?

### ISSUE THREAD

**Issue by laurenancona** [18F/laptop#149]
Perhaps as an optional customization; useful for anyone working on Federalist sites using Jekyll templates, et al.

**Comment by monfresh** [comment]
Typically, Ruby gems are installed on a per-project basis via the `Gemfile`. I'm not sure we would want to install Jekyll globally on a user's machine. The expectation is that Federalist sites have a `Gemfile` that defines the required gems, and provide some kind of installation script that runs `bundle install` (or directs users to run that command in the Readme). For example: https://github.com/18F/handbook#development

**Comment by laurenancona** [comment]
Makes sense.
Came across a situation where I cloned an 18f Jekyll template today on my work machine & had run Laptop, so assumed Jekyll + depends were installed, but were not. Will check that repo & file there if necessary. Thanks!
