### ISSUE TITLE
Script fails on Xcode

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/laptop#153]
I'm consistently getting a failure at the point of installing xcode and the xcode CLTs:

```
Installing Command Line Tools (macOS Sierra version 10.12) for Xcode
Error downloading Command Line Tools (macOS Sierra version 10.12) for Xcode: “Command Line Tools (macOS Sierra version 10.12) for Xcode” could not be verified.
Done.

Error downloading updates.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
Password:
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
failed
```
I think it may be due to xcode 9 dropping today.

### OS X version you are using
12.6

### Did you recently upgrade from a previous OS X version?
No

### Are you running the script on a fresh OS X installation?
Yes

### Did you have any of the following tools installed before running the script?
- Xcode No
- Apple's command line tools No
- Anything the script installs (see "What it sets up" in the README) - if anything was installed prior to xcode, it's probably installed ok.

**Comment by tbaxter-18f** [comment]
OK, I can confirm now that it appears to be the change in Xcode causing the failure. 

As a workaround, you can download xcode 9 and the CLTs here: https://developer.apple.com/download/more/ 

Note that you will need to accept the xcode license, either by opening xcode and clicking to agree or running:
    sudo xcodebuild -license


Once you've done that, it should work.

**Comment by afeld** [comment]
See https://github.com/18F/laptop/pull/162#issuecomment-523177750, which may help.
