### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by rahearn** [18F/laptop#164]
Is there any interest in adding fish shell support alongside zsh and bash?

I can take a stab at implementing if there's value there.

**Comment by mgwalker** [comment]
I think it's a good idea, especially adding an extra check around [figuring out the shell file](https://github.com/18F/laptop/blob/master/mac#L65).  I think a sensible workflow is: if the user is using zsh or fish, leave it alone (but of course, get the path to the shell rc/profile file); if they're using bash, offer to switch to zsh as the 18F recommendation.

**Comment by mgwalker** [comment]
Closed by #169
