### ISSUE TITLE
Update README and script comments on rbenv vs. chruby

### ISSUE THREAD

**Issue by paolov18F** [18F/laptop#178]
The script outputs this:

`We recommend chruby and ruby-install over RVM or rbenv`

But in the lines above, the script wants to install rbenv.  

` append_to_shell_file "status --is-interactive; and source (rbenv init -|psub)"
    # rbenv currently doesn't have a convenience version to use, e.g., "latest",
    # so we check for the latest version against Homebrew instead.
    latest_ruby="$(brew info ruby | grep -E -o "\d+\.\d+\.\d+" | head -1)"
    if ! rbenv versions | ag "$latest_ruby" > /dev/null; then
      rbenv install "$latest_ruby"
      rbenv global "$latest_ruby"
      eval "$(rbenv init - bash)"
    fi
    ;;
`
So perhaps the output message recommending chruby and the README should be updated if rbenv is now recommended over chruby.

**Comment by rahearn** [comment]
rbenv is recommended mostly for `fish` shell users, where chruby doesn't work. The README and script could probably be clearer about that.
