### ISSUE TITLE
reduce scope/steps in the laptop script

### ISSUE THREAD

**Issue by afeld** [18F/laptop#189]
Follow-up to https://github.com/18F/laptop/issues/184#issuecomment-511050994. In short, this is not being maintained, and has opinions that are not shared across TTS, so let's drastically reduce its scope. My proposal of what should remain in scope, either in the script itself or as documentation (pointing to canonical instructions).

> - XCode command-line tools
> - Homebrew
> - git-seekrets, or a suitable equivalent (#185). It's 18F policy - the spirit of it is that we protect ourselves from accidentally committing secrets is still very valid.
> - Git configuration

- [ ] Delete the rest from the repository

**Comment by JJediny** [comment]
I was recently refreshed and documented the steps I took to reestablish my environment: https://docs.google.com/document/d/1MeCa0owF-MmXXF38tHJ3wFZKTkctFatF0C3GOp-Qb7k/edit#heading=h.o9uj4a2zeaz9

**Comment by its-a-lisa** [comment]
https://github.com/18F/laptop/pull/190

**Comment by its-a-lisa** [comment]
https://github.com/18F/laptop/pull/150

**Comment by JJediny** [comment]
These might be good replacements for git-seekrets, moving the configuration burden to the repos being worked on using a yaml configuration file in version control would allow custom pre-commit checks specific to whatever project is being worked on with: https://pre-commit.com/#intro

a secret pre-commit check could use:
- https://github.com/Yelp/detect-secrets
- https://github.com/zricethezav/gitleaks

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
