### ISSUE TITLE
Include Python 2 and Python 3?

### ISSUE THREAD

**Issue by bsweger** [18F/laptop#2]
Not sure what other Python devs at 18F do, but I installed Python 2 and Python 3 on my laptop. I find it handy to default to 3 with an option to point new virtualenvs to Python2 in specific cases.

**Comment by konklone** [comment]
Strong recommendation for [using pyenv](https://github.com/konklone/ubuntu/blob/master/workflow.md#python-with-pyenv) to manage multiple versions, rather than system installation. It keeps your system dependencies separate from development dependencies, eliminates the need for sudo to manage language use, and plays nicely with virtualenv and virtualenvwrapper.

**Comment by bsweger** [comment]
I have python 2 & 3 installed via homebrew and haven't had to manage anything with sudo. You can specify a specific Python version when running mkvirtualenv, and that seems to be working.

That said, if pyenv makes it easier to manage Python 2/3 with no drama when working with virtualenvwrapper, that would be swell.

**Comment by monfresh** [comment]
I don't have a strong opinion on this since I'm new to Python, but if Homebrew works, then that seems to be the easiest option and wouldn't require installing an additional tool. But I'd like to hear from more Python users. @jackiekazil, @kaitlin, @khandelwal @cmc333333 ?

**Comment by konklone** [comment]
I know @seanherron's had some experience, as well.

**Comment by kaitlin** [comment]
For me, pyenv is way overkill and a solution in search of a problem. I use brew to install py2 and py3 and similar to @bsweger, I default to py3 most of the time.

**Comment by jackiekazil** [comment]
+1 --
brew install py2 & py3, then
mkvirtualenv w/ the version of python I need. I don't use pyenv either. I
never saw a need for it with virtualenv
default to py3 now.

**Comment by monfresh** [comment]
The people have spoken. I will install py3 via brew in the default script.
