### ISSUE TITLE
Failed 

### ISSUE THREAD

**Issue by jkhrpr** [18F/laptop#23]
Gave me this: 

Installing cloudfoundry-cli ...
==> Installing cloudfoundry-cli from pivotal/homebrew-tap
==> Downloading https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.12.2&source=homebrew
==> Downloading from http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.12.2/cf-darwin-amd64.tgz
🍺  /usr/local/Cellar/cloudfoundry-cli/6.12.2: 2 files, 23M, built in 3 seconds
The file /Users/NewsMBP/Applications/GitHub.app does not exist.

**Comment by monfresh** [comment]
Hi @jkhrpr. Thanks for using the laptop script. Although it looks like it failed at the very end, the script actually installed all the tools successfully. The very last thing the script does is it launches the GitHub app when it sees that you don't have an SSH key called `github_rsa.pub`.

In your case, you already have the GitHub app installed, so the script skipped it, and therefore never installed GitHub in your user's Applications folder, which is where the script looks for the app.

This is a known issue that we will be fixing soon. See https://github.com/18F/laptop/pull/14 for more details.

All this is to say that you can ignore that error message. You should be good to go.

**Comment by jkhrpr** [comment]
Great, thanks! I just wasn't sure if it had installed everything yet, so I
wanted to be sure.

On Mon, Aug 31, 2015 at 7:02 PM, Moncef Belyamani <notifications@github.com>
wrote:

> Hi @jkhrpr <https://github.com/jkhrpr>. Thanks for using the laptop
> script. Although it looks like it failed at the very end, the script
> actually installed all the tools successfully. The very last thing the
> script does is it launches the GitHub app when it sees that you don't have
> an SSH key called github_rsa.pub.
>
> In your case, you already have the GitHub app installed, so the script
> skipped it, and therefore never installed GitHub in your user's
> Applications folder, which is where the script looks for the app.
>
> This is a known issue that we will be fixing soon. See #14
> <https://github.com/18F/laptop/pull/14> for more details.
>
> All this is to say that you can ignore that error message. You should be
> good to go.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/laptop/issues/23#issuecomment-136523284>.
>



-- 

*Jake Harper*

Health Reporter

WFYI/Side Effects Public Media

jharper@WFYI.org

Phone: 317-614-0482

Cell: 202-997-6681

@jkhrpr <https://twitter.com/jkhrpr>

**Comment by fureigh** [comment]
Thanks for the above, as I ran into this issue too. :+1:
