### ISSUE TITLE
pull some things from Strap

### ISSUE THREAD

**Issue by afeld** [18F/laptop#25]
Just heard about this project:

https://github.com/mikemcquaid/strap

which has some cool [features](https://github.com/mikemcquaid/strap#features) we should steal. Notably:
- Installing XCode command-line tools
- Adding a message to the login screen
- Encrypting the hard drive

**Comment by monfresh** [comment]
Sounds good. We already install the CLT. Without them, nothing else in the script would work :)

**Comment by mgwalker** [comment]
Closing this one as deprecated:
- Xcode CLT is installed
- central management software adds a message to the login screen
- central management software also enables FileVault
