### ISSUE TITLE
Update & test for OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by yozlet** [18F/laptop#26]
This may be rather nasty as I _believe_ Homebrew won't install on a new Mac due to the new [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection) features - `/usr/local/` needs to be created, and that needs the [Recovery Mode dance](https://en.wikipedia.org/wiki/System_Integrity_Protection).

**Comment by monfresh** [comment]
I will test this on my spare laptop that I use for testing things like this on clean OS X installations.

**Comment by monfresh** [comment]
I tested the script on a clean installation of El Capitan and it worked perfectly (as long as phantomjs was commented out). Note that `/usr/local` is not protected, as mentioned in the Wiki article you linked to:
```
 Among the protected directories are these: /System, /bin, /sbin and /usr (but not /usr/local)
```
