### ISSUE TITLE
GitHub.app does not exist

### ISSUE THREAD

**Issue by jbarnicle** [18F/laptop#29]
I believe the script thinks I have the Github app installed (I don't currently).  Here is the last bit of the log output.  I'm on Mac OSX Yosemite 10.10.5.

Installing cloudfoundry-cli ...
==> Installing cloudfoundry-cli from pivotal/homebrew-tap
==> Downloading https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.13.0&source=homebrew
==> Downloading from http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.13.0/cf-darwin-amd64.tgz
🍺  /usr/local/Cellar/cloudfoundry-cli/6.13.0: 2 files, 19M, built in 3 seconds
The file /Users/michaelbarnicle/Applications/GitHub.app does not exist.

**Comment by monfresh** [comment]
This was due to the Cask version of GitHub for Mac being renamed from `github` to `github-desktop`. It has been fixed in #28. Please download the latest version and try again.
