### ISSUE TITLE
Include virtualenvwrapper?

### ISSUE THREAD

**Issue by bsweger** [18F/laptop#3]
If the setup script is pip installing virtualenv, makes sense to install virtualenvwrapper too. Hard to imagine using virtualenv w/o the handy shortcuts and project structure provided by virtualenvwrapper.

**Comment by monfresh** [comment]
Sounds good to me. I have little experience with Python, so recommendations from more experienced people is welcome.

**Comment by monfresh** [comment]
Fixed by #5.
