### ISSUE TITLE
Customize zsh prompt to display username and other useful info

### ISSUE THREAD

**Issue by monfresh** [18F/laptop#32]
By default, the zsh prompt does not display your OS username, or your current directory, unlike the default bash prompt. Since the script changes the shell to zsh, it should also update the prompt to display useful info, such as the username, current directory, and current ruby version.

**Comment by LinuxBozo** [comment]
Would a framework like [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) be overkill here?

**Comment by monfresh** [comment]
OMZ is popular enough that I would add it as an option in `.laptop.local`, but not in the main script in case some might want to use something else, or their own customization.

**Comment by cwonrails** [comment]
Something like [pure-prompt](https://github.com/sindresorhus/pure) might strike the right balance here.

**Comment by monfresh** [comment]
Thanks! I will look into it.

**Comment by mgwalker** [comment]
Similar to #36, this should be an individual choice.  Added it as a commented-out install in `.laptop.local`. #163
