### ISSUE TITLE
Use GNU based coreutils instead of built-in OSX BSD style utilities

### ISSUE THREAD

**Issue by LinuxBozo** [18F/laptop#36]
This is more of a question/discussion point than actual _issue_, but considering most deployment/VM platforms are Linux based, which use the suite of GNU utilities (`ls`, `basename`, `cut`, etc), would it make sense to have brew install `coreutils` and insert those into the $PATH first position. This would make sure that any time you are using these utilities, they are consistent both locally, and in a deployed/VM environment.

**Comment by monfresh** [comment]
That's a great idea, but I think this type of configuration is best left as a choice. I'd like to keep the default script as lean as possible, and anything that's not critical can go in the custom script. I would add the appropriate setup in a new commented-out section in [.laptop.local](https://github.com/18F/laptop/blob/master/.laptop.local).

**Comment by mgwalker** [comment]
Agreed this should be an individual choice.  Added it as a commented-out install in `Brewfile.local`. #163
