### ISSUE TITLE
Use Brewfiles rather than bespoke brew-automation code

### ISSUE THREAD

**Issue by mogul** [18F/laptop#40]
I found out that brew can take a `Brewfile` now and combined with `brew cask` a lot of the bespoke code in the laptop script for automation of brew is probably redundant. The user-facing messages aren’t as friendly, but it does make it very tidy to maintain everything… See [my bootstrap script](https://github.com/mogul/dotfiles/blob/master/mac-bootstrap) and [my Brewfiles](https://github.com/mogul/dotfiles/tree/master/mac). You can `brew bundle --file=$BREWFILE` repeatedly with no ill effects due to the packages already being installed.

Brewfiles can include “tap” and “brew” commands, but they don’t understand “cask”. So casks still need to get managed separately unless we make it work, then send a PR upstream. (Alternatively I suppose it’s really not much more convenience over a loop that simply executes brew with the rest of the line in the Brewfile when it comes right down to it, and that would handle casks too. So maybe it could just be rewritten that way.)

**Comment by monfresh** [comment]
Done via #55
