### ISSUE TITLE
SHA1 error when running laptop script

### ISSUE THREAD

**Issue by porta-antiporta** [18F/laptop#45]
When running the laptop script, I got the following error in the laptop.log file

```
Installing cf-cli ...
==> Installing cf-cli from cloudfoundry/tap
==> Downloading https://cli.run.pivotal.io/stable?release=macosx64-binary&version=6.15.0&source=homebrew
==> Downloading from http://go-cli.s3-website-us-east-1.amazonaws.com/releases/v6.15.0/cf-cli_6.15.0_osx.tgz
Error: SHA1 mismatch
Expected: 1179c8e60395bb8a6b6bc5eb2880a3470106dec6
Actual: fba9d38ea53c794e58fb4273658c07d13b771722
Archive: /Library/Caches/Homebrew/cf-cli-6.15.0.0&source=homebrew
To retry an incomplete download, remove the file above.
```

For reference below is the contents of .laptop.local (installing the optional apps sans firefox)

```
#!/bin/sh
fancy_echo 'Executing laptop.local'

brew_cask_install 'atom'
# brew_cask_install 'firefox'
brew_cask_install 'iterm2'

brew_install_or_upgrade 'vim'
brew_install_or_upgrade 'ctags'
brew_install_or_upgrade 'tmux'
brew_install_or_upgrade 'reattach-to-user-namespace'

brew_install_or_upgrade 'go' && append_to_file "$HOME/.zshrc" 'export PATH="$PATH:/usr/local/opt/go/libexec/bin"'
```

**Comment by monfresh** [comment]
Thanks for the report. This is a cloudfoundry/homebrew-tap issue. I just reported it: https://github.com/cloudfoundry/homebrew-tap/issues/3

**Comment by monfresh** [comment]
In the meantime, I will see if I can detect that the installation failed and skip it to allow the rest of the script to run.

**Comment by monfresh** [comment]
Oh, and if you want the rest of the script to run, you can comment out line 286: `brew_install_or_upgrade 'cf-cli'` and run the script again.

**Comment by porta-antiporta** [comment]
i commented out that line on my local and reran the script.

now it's asking me to agree to the xcode license.  (when i first ran the script, it asked me to download a text/command line tool like xcode).  are we allowed to do that?  in GSA orientation, they mentioned that we shouldn't agree to any licenses/eulas.

'''
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license
failed
'''

**Comment by monfresh** [comment]
Yes, we are allowed to install the command line tools and agreeing to the Xcode license afaik. I haven't seen this license issue before, though. When you first ran the script, what option did you choose in the popup?

Could you please quit and relaunch Terminal, fetch the latest version of the script, and try running it again?

**Comment by porta-antiporta** [comment]
the latest version of the script worked. thanks!
