### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by neilmartis** [18F/laptop#47]
I have Linux machine and plan to execute the script just wanted to be sure if it will run ok.

**Comment by monfresh** [comment]
Hi @neilmartis. As mentioned in the Readme, this script is only supported on OS X. It uses Homebrew to install most tools, so it won't work on Linux. We don't plan on supporting Linux as we don't have enough people using it to be able to test it and maintain it.

This repo is a fork of thoughtbot's laptop, and they dropped support for Linux about a year ago, but you can still access the script here to see if it works for you: https://github.com/thoughtbot/laptop/tree/39768b19959f74724ed0c0ea92e5b2f6f78e45c1#linux-1

**Comment by neilmartis** [comment]
Thanks Moncef.I will try it out and let you know.I have sent you a linkedin request
