### ISSUE TITLE
Include Postgres install?

### ISSUE THREAD

**Issue by jessieay** [18F/laptop#50]
Don't see Postgres in the list of installed things. It *is* part of the thoughtbot laptop script. https://github.com/thoughtbot/laptop

Is there a reason it is not included here?

**Comment by monfresh** [comment]
Not sure why it's not showing up for you, but it's there:

https://github.com/18F/laptop/blob/master/mac#L152
https://github.com/18F/laptop#what-it-sets-up

**Comment by jessieay** [comment]
d'oh - somehow missed that when scanning through list. sorry! closing
