### ISSUE TITLE
rvm fails to install if users have gpg installed

### ISSUE THREAD

**Issue by stvnrlly** [18F/laptop#70]
It looks like v1.26.0 of `rvm` introduced signed releases, so installation now requires that users [download the maintainer's public key](https://rvm.io/rvm/install). If `gpg` isn't installed, it looks like it just skips the check, so most people running this script for the first time won't run into the problem. If you have `gpg` installed, though, this script will now fail at that point.

**Comment by monfresh** [comment]
Thanks! Let me know if you were planning on submitting a PR to fix this. Otherwise, I'll do it.

**Comment by stvnrlly** [comment]
Well, it seemed like a bigger question to me. The error message tells me to only grab the key if I trust the maintainer, which I was squeamish about. Looking into it more, I see that the key is also on keybase, which I understand a little bit more.

It still doesn't feel great, but if others are also ok with the setup I can PR it.

**Comment by monfresh** [comment]
Closing this because we are no longer installing RVM. We've switched to `chruby` and `ruby-install`.
