### ISSUE TITLE
Instructions on how to run BATS locally for git-seekrets

### ISSUE THREAD

**Issue by jcscottiii** [18F/laptop#78]
Once #74 is addressed, it would be helpful for developers to have instructions on how to setup and run the tests locally.

The instructions (and possible additional script logic) should preserve their current rules prior to running the tests locally and should restore their rules after the tests.

Extra considerations:
May want to trap the `Ctrl-C` signal (and maybe other signals) so that if a developer pushes Ctrl-C, it will cleanup before exiting. Example: `A clean_up function` section in http://linuxcommand.org/wss0160.php

#### Acceptance Criteria

- [x] Documentation for #74

**Comment by alain-hoang** [comment]
See #74 for pointer to documentation
