### ISSUE TITLE
Update seekrets-install script to use generated binary from build script

### ISSUE THREAD

**Issue by alain-hoang** [18F/laptop#91]
The `seekrets-install` script currently uses the `go get` method for installing the `git-seekrets` command.

A build script that can generate the `git-seekrets` binary is already inside of the repository.    Until regular official build releases from upstream are ready, the`seekrets install` script could install the binary artifact generated from the build script and avoid duplicating the effort from the build script.

**Comment by alain-hoang** [comment]
Document the process of updating the binary should also be provided

**Comment by LinuxBozo** [comment]
Closed by #103
