### ISSUE TITLE
identify a go installation method (not dependent on package managers such as brew)

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/laptop#92]
For purposes of documentation of git seekrets, etc. let's suggest a go installation method.

It should be noted that this require's Xcode and Apple's command line tools

Optionally: indicate similarities with Linux go installation methods

**Comment by rogeruiz** [comment]
I believe we're sticking with leveraging a binary release. I think it might make sense maybe to include this sort of documentation in https://github.com/18F/git-seekret. We should only talk about leveraging or including `git-seekret` in this repo and have the actual source code to `git-seekret` talk about installation.
