### ISSUE TITLE
Testing that GitHub Desktop uses git-seekret hooks

### ISSUE THREAD

**Issue by alain-hoang** [18F/laptop#95]
Once installation and setup for git-seekrets is finished, tests with the GitHub Desktop client should be performed in order to verify that the GitHub Desktop client will also work with git-seekrets.

Considerations for this task

- [ ] git seekrets has been installed
- [ ] git seekrets is configured to detect baseline rule of secrets
- [ ] hooks are in place for repos that will be tested

**Comment by rogeruiz** [comment]
This has been visually verified by me and @LinuxBozo so I'm not sure if we need to keep this around. 🤔

**Comment by alain-hoang** [comment]
I have also verified this
