### ISSUE TITLE
NVM_DIR not set in shell by default

### ISSUE THREAD

**Issue by cryptofilegsa** [18F/laptop#98]
after a clean install, I needed to run this in order to proceed with the installation of laptop-seekret:
export NVM_DIR="/Users/username/.nvm"

would be nice to have NVM_DIR set automatically with the initial installation.

**Comment by monfresh** [comment]
The initial installation of NVM does set NVM_DIR by adding the following lines to your `.zshrc` file:
```
export NVM_DIR="/Users/username/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```
Can you confirm whether or not your `.zshrc` file contains those lines?

Also, did you quit and relaunch Terminal before running laptop-seekret?

**Comment by monfresh** [comment]
@cryptofilegsa Hi. I'm not sure if you saw my previous comment. Can you please respond so I can determine how to proceed? Thanks!

**Comment by monfresh** [comment]
I'm closing this for now. I verified that the export line is added to .zshrc. Feel free to reopen if you are able to reproduce after relaunching Terminal (or sourcing your .zshrc after running the laptop script).

**Comment by cryptofilegsa** [comment]
fixed, worked after I caught the changes in brew
